Update README.md
vostok-project/website pull request #5
Opened 2017-10-09 14:36 UTC by dotcard

Надо ещё с instrument/instrumented что-то сделать. Что в русском описании на этом месте?

2017-10-11 12:30 UTC, igorlukanin requested changes

2017-10-11 12:30 UTC, igorlukanin commented on README.md
> +<!-- Yandex.Metrika counter --> <script type="text/javascript" > (function (d, w, c) { (w[c] = w[c] || []).push(function() { try { w.yaCounter46187796 = new Ya.Metrika({ id:46187796, clickmap:true, t
Что тут поменялось? Надо откатить

2017-10-11 12:30 UTC, igorlukanin commented on README.md
> +Vostok has everything .NET developers need to create distributed systems. It enables intra-cluster interaction between microservices, collects their logs and metrics, and distributes traces out of th
Я согласен с исправлениями в «distributes» и «and more».

Остальные изменения не делают лучше. Предлагаю их откатить. В прежней версии лучше синтаксис и корректно используется оксфордская запятая

2017-10-11 12:30 UTC, igorlukanin commented on README.md
> +Every Vostok-instrumented microservice collects that data types out of the box. No additional confuguration or code is required.
Неудачная правка, потому что о «типах данных» в исходной версии не говорится. Думаю, что не стоит вводить новый термин. Предлагаю переформулировать или откатить

2017-10-11 12:30 UTC, igorlukanin commented on README.md
> +Applications use Vostok's interfaces to make custom logs and metrics. Any outgoing request via provided *[Cluster Client](https://github.com/vostok/clusterclient)* is included to the distributed trac
Неудачная правка, потому что вводятся новые термины: «интерфейсы Востока» и «сервис». Также не понял, по какой причине появились определённые артикли. Предлагаю полностью откатить

2017-10-11 12:33 UTC, igorlukanin commented
Спасибо за правки! Предлагаю немного улучшить их перед мержем.

> Надо ещё с instrument/instrumented что-то сделать. Что в русском описании на этом месте?

Насколько я знаю, «instrumentation» — общепринятый и довольно распространённый термин. Что именно хочется сделать? Зачем?

Никакого русского описания нет :)

2017-10-13 13:00 UTC, igorlukanin commented on README.md
> +Vostok has everything .NET developers need to create distributed systems. It enables intra-cluster interaction between microservices, collects their logs and metrics, and distributes traces out of th
Частично внёс исправления, нужен rebase.

2017-11-20 10:03 UTC, beevee commented
Документацию значительно переписали, больше не актуально.

2017-11-20 10:03 UTC, closed without merging